language: java
notifications:
  hipchat:
    rooms:
      secure: PtixR6CccsLl3zBliXBYsKDp/ZVmYfMG5ylt9sQ/3Y1o9SoW/GicV2xidCvkxdzgAWBvX2+4W86Fa8c3qBvYSm/vmrEeT/1GdenqB8yCnG5VnzcZo2VyKw1KJW/AfwMsgKF2ydqEFrg/d7OgNKj2NfOi0fdOmdREnQqa4qw90zY=
deploy:
  provider: releases
  api_key:
    secure: CFtWQ+Jar0IrDbfOTDS8pWCg4zZLclTqK+tH/ttUml/m7ukUjyOfO+xc2c00jnjkvq3wrdNB6bBcZCFqptG4GKGUgsQ+ILVL0Kob6hqizw8hKPN1DrnC+rgQPN/kfvwlXMjcsdvXmjZg6D3iKrfx3aZFhO8ohh1vgEYYzUOzZaM=
  file: build/libs/elasticsearch-plugin-1.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true 
    repo: xebialabs-community/elasticsearch-plugin
