language: java
notifications:
  slack:
    secure: JdOkvUfc+hSq0BdptrTa7q5Gqc8uIs5N6mLE7PFKZPzxfgIqUT/8itrvaqCUJMTh6AzAZLy4dUk2v0VQJDxfbloVwJ6jbORIWWOojK7L7VXf4VAkt3j0TZ8R0ZwPIzlBpegJQxB/6ABIKTT1tQxR1aCdY24y281mcBrGQUy9cno=
deploy:
  provider: releases
  api_key:
    secure: TMxYmQ7OESE2L1/GTv9fgtw65xxmAaW66FVtQYrY6Rvb+j2epEVQ3HV1EY8BPewQqpMfqYly0LI72fd1XQsK3EBrosqzASkZ7q2P5eMIg9p5uTZOydWR69KLuin+bx5KQKKmZM+E1HskrNVK6ba41VlYKXqkCSjhihe1nv8PIjU=
  file: build/libs/elasticsearch-plugin-1.1.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/elasticsearch-plugin
